// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB8325_uENchKld-TcWA2jhh_3mofzy7E',
    appId: '1:785851859485:web:248e2ccd28b46a420dbcf4',
    messagingSenderId: '785851859485',
    projectId: 'areadr-8ba75',
    authDomain: 'areadr-8ba75.firebaseapp.com',
    storageBucket: 'areadr-8ba75.firebasestorage.app',
    measurementId: 'G-DLNK7EJB91',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJGkJL5GZ7FEDtMTAw5QHtp9bnVFUOpUQ',
    appId: '1:785851859485:ios:6ff122b43e5fd87e0dbcf4',
    messagingSenderId: '785851859485',
    projectId: 'areadr-8ba75',
    storageBucket: 'areadr-8ba75.firebasestorage.app',
    iosClientId: '785851859485-scdufejopipjeundrijklfktn94h2ikp.apps.googleusercontent.com',
    iosBundleId: 'com.example.areadr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB8325_uENchKld-TcWA2jhh_3mofzy7E',
    appId: '1:785851859485:web:aae64f7d56c8cd8e0dbcf4',
    messagingSenderId: '785851859485',
    projectId: 'areadr-8ba75',
    authDomain: 'areadr-8ba75.firebaseapp.com',
    storageBucket: 'areadr-8ba75.firebasestorage.app',
    measurementId: 'G-VT3SE0X5E0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJGkJL5GZ7FEDtMTAw5QHtp9bnVFUOpUQ',
    appId: '1:785851859485:ios:6ff122b43e5fd87e0dbcf4',
    messagingSenderId: '785851859485',
    projectId: 'areadr-8ba75',
    storageBucket: 'areadr-8ba75.firebasestorage.app',
    iosClientId: '785851859485-scdufejopipjeundrijklfktn94h2ikp.apps.googleusercontent.com',
    iosBundleId: 'com.example.areadr',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGonaBd3L1_kzDK1Z2ZRMk5iftbOdhdNg',
    appId: '1:785851859485:android:a2529556103aa5de0dbcf4',
    messagingSenderId: '785851859485',
    projectId: 'areadr-8ba75',
    storageBucket: 'areadr-8ba75.firebasestorage.app',
  );

}